// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJltECjMAf0YWtGnFEorjuh6q53B5aOrA',
    appId: '1:426493695547:web:48992150a1e986693bee1e',
    messagingSenderId: '426493695547',
    projectId: 'ezbooking-33cb0',
    authDomain: 'ezbooking-33cb0.firebaseapp.com',
    storageBucket: 'ezbooking-33cb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgw-c4zdaEkbr4QbGGX6MraqZpAzQ6vK8',
    appId: '1:426493695547:android:e907da7d3da60d913bee1e',
    messagingSenderId: '426493695547',
    projectId: 'ezbooking-33cb0',
    storageBucket: 'ezbooking-33cb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAENyXcvP17LE-uE9ezkK555tDXoGJ1aJ4',
    appId: '1:426493695547:ios:643cba72c1adda253bee1e',
    messagingSenderId: '426493695547',
    projectId: 'ezbooking-33cb0',
    storageBucket: 'ezbooking-33cb0.firebasestorage.app',
    iosBundleId: 'com.thuanht.oezbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAENyXcvP17LE-uE9ezkK555tDXoGJ1aJ4',
    appId: '1:426493695547:ios:643cba72c1adda253bee1e',
    messagingSenderId: '426493695547',
    projectId: 'ezbooking-33cb0',
    storageBucket: 'ezbooking-33cb0.firebasestorage.app',
    iosBundleId: 'com.thuanht.oezbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJltECjMAf0YWtGnFEorjuh6q53B5aOrA',
    appId: '1:426493695547:web:378e730c90a982c43bee1e',
    messagingSenderId: '426493695547',
    projectId: 'ezbooking-33cb0',
    authDomain: 'ezbooking-33cb0.firebaseapp.com',
    storageBucket: 'ezbooking-33cb0.firebasestorage.app',
  );
}
